config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  validates :identificacion, :nombre, presence: true
  validates :identificacion, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:placa, :modelo, :color)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      flash[:notice] = "Guardado correctamente"
      redirect_to @person
    else
      render :new
    end
  end

  def edit
  end

  def show
    @person = Person.find(params[:id])
  end

  private
    def person_params
      params.require(:person).permit(:identificacion, :nombre, :edad, :avatar, :avatar_cache, :remote_avatar_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # type = 'warning' if type == 'notice'
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :placa %>
    <%= f.input :modelo %>
    <%= f.input :color %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Modelo</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.placa %></td>
        <td><%= car.modelo %></td>
        <td><%= car.color %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @car.placa %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @car.modelo %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/home/index.html.erb
<h1>DASHBOARD</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to "Nueva persona", new_person_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manuel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= custom_bootstrap_flash %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1>People#index</h1>
<p>Find me in app/views/people/index.html.erb</p>

app/views/people/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>AQUI ESTA NEW</h1>

      <%= simple_form_for @person, html: { multipart: true } do |f| %>
        <%= f.input :identificacion %>
        <%= f.input :nombre %>
        <%= f.input :edad %>
        <%= f.input :avatar %>
        <%= f.input :avatar_cache, as: :hidden %>
        <%= f.input :remote_avatar_url %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/people/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <dl>
        <dt>Cedula</dt>
        <dd><%= @person.identificacion %></dd>
        <dt>Nombre</dt>
        <dd><%= @person.nombre %></dd>
        <dt>Edad</dt>
        <dd><%= @person.edad %></dd>
      </dl>
      <%= image_tag(@person.avatar_url) if @person.avatar? %>
    </div>
  </div>
</div>